### ISSUE TITLE
`If` necesario?

### ISSUE THREAD

**Issue by javibravo** [JorgeGBravo/ApiRestVirtualWaiter#1]
Es este `if` necesario?:
https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/AuthController.php#L71

En la busqueda anterior ya estas filtrando por `email`, por lo que no debería haber ningún otro email:
https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/AuthController.php#L67

**Comment by JorgeGBravo** [comment]
Ahora que me lo planteas, es cierto si encuentra o no el mail, ya estaría la condición.
