### ISSUE TITLE
`RegisterUser` and `RegisterUserManager` - cual es la diferencia y porque estan en distintos controladores?

### ISSUE THREAD

**Issue by javibravo** [JorgeGBravo/ApiRestVirtualWaiter#2]
`RegisterUserManager` en `AuthController`:
https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/AuthController.php#L14

Parece identico a `RegisterUser` en `UserController`:
https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/UserController.php#L13

- Cual es la finalidad de duplicarlos en distintos controladores?
- Hay alguna diferencia de la que yo no me he percatado?

**Comment by JorgeGBravo** [comment]
En verdad no hay ninguna, he suprimido el manager y aplique isAdmin como valor de entrada a determinar.
