### ISSUE TITLE
Buscar al usuario por el CIF?

### ISSUE THREAD

**Issue by javibravo** [JorgeGBravo/ApiRestVirtualWaiter#3]
No estoy seguro de lo que se esta haciendo aqui:

https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/Controller.php#L22-L25

**Comment by JorgeGBravo** [comment]
En esa función compruebo si existe o no, usuario o comercio ya que el cif en ambos son únicos.
