### ISSUE TITLE
Cada vez que se crea un comercio se crea un usuario nuevo?

### ISSUE THREAD

**Issue by javibravo** [JorgeGBravo/ApiRestVirtualWaiter#4]
https://github.com/JorgeGBravo/ApiRestVirtualWaiter/blob/7e60a0c1d8757bc8d84c3a8033ef234c1c965e48/app/Http/Controllers/CommerceController.php#L31

**Comment by JorgeGBravo** [comment]
No, comercios.  Problemas con el copia y pega
